[package]
name = "shol"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.22.1", features = ["lexer"] }
logos = "0.14"
urlencoding = "2.1.3"

[build-dependencies]
lalrpop = "0.22.1"
